### ISSUE TITLE
Where to find compiled extension?

### ISSUE THREAD

**Issue by endo64** [moisseev/sqlite-md5#2]
Where can I find the compiled version of this extension (for Windows?)
Or the only way to use it is compiling by myself?

**Comment by moisseev** [comment]
I don't know. I don't think someone provides any packages for this extension.

**Comment by endo64** [comment]
Actually I couldn't find any compiled package for any of the extensions, also surprised that SQLite doesn't have any hashing function built-in. 
Thank you for the response.
